### PR TITLE
massive rebuilding

### PR DESCRIPTION
**Pull request by tobciu**
massive rebuilding of the structure and using Yii2 and Humhub functionality, added Admininistration so nobody has to rewrite their config ;-)

### CODE REVIEW

**Comment by tobciu** [comment]
feel free to add additional authors :-)

**Comment by petersmithca** [comment]
Thank you! Wow, I'll have a look when I get home, as for authors I should have done that before, I'm not that used to git

**Comment by Felli** [comment]
Really love what this brings to the table, the only problem that I'm having is that the "Online Members" is below the messages which messes with the actual chat (Viewing wise), other than this it looks pretty good!

**Comment by petersmithca** [comment]
@Felli Im not seeing any visual changes or not noticeable to me anyway.

**Comment by tobciu** [comment]
@petersmithca the only visual change is the submit-button, if sending a message, the button will be disabled and an indicator will be visible

**Comment by Felli** [comment]
On my end I'm seeing some problems with the bright version of the chat, but not with the dark. lol

## Bright



## Dark

**Comment by petersmithca** [comment]
I've merged it. More yours now than mine! Put your name on top in authors

**Comment by WebCrew** [comment]
woow awesome jobs mates thx @tobciu @petersmithca @Felli 
What a cool teamwork :+1:

**Pull request merged**
