### PR TITLE
I`ve done some style changes

### PR DESCRIPTION
**Pull request by WebCrew**
button_blue 

Hi Peter,

insert this new styled button to assets folder please. 
Name it: button_blue.png

You can see a working demo of the chat here:
[http://hh.palareas.de/dashboard]
I hope You like the new style. Its nothing more to do, just upload the module to humhub and check it out.

Kind regards, Andreas Holzer

### CODE REVIEW

**Comment by Felli** [comment]
Nicely done. :+1:

**Comment by WebCrew** [comment]
THX Sarah ;)

**Comment by Felli** [comment]
@WebCrew question is there any way of moving the send button next to the message box?

**Comment by WebCrew** [comment]
You mean without the bright gaps, close to the text input field box? So that it looks like one line? Yes its possible, but only if we do the button with pure css. At the moment the button is a image and its hard to make it float left/right (responsive) for all screen resolutions.

I try something tomorrow and drop you a update if it works.

I will also do a secend style, a bright one.

**Comment by Felli** [comment]
Cool, look forward to seeing it. :smile:

**Comment by WebCrew** [comment]
Huhuu Sarah the job is done :)
Uninstall Your Chat Module use the new one and install it again...
then,
have fun using it :)

newchatstyle

**Comment by Felli** [comment]
@WebCrew Looks really good, I'll see what I can do color wise, as well as support wise for features such as emoji/emoticon support. :+1:

**Comment by WebCrew** [comment]
@Felli Thanks for Your opinion Sarah.

Yeahh I know You are friend with PHP (I m only a beginner with php) but I think we can implement Emojie with easy cause we can use the feature right from HumHubs Spaces System. I ll also try to integrate auto link detection feature and maybe also to integrate the sahre Drop Box files thing, but it needs time :)

**Comment by Felli** [comment]
@WebCrew That's a good idea, I'll try looking into this myself as well. :smile:

**Comment by WebCrew** [comment]
For the link detection thing I have found a nice yii2 based script here at GitHub. We will become a nice chat if we do teamwork all together ;)

**Comment by petersmithca** [comment]
I'll merge this when I get home and have a look

**Comment by michaelscheurer** [comment]
This is a very nice module for humhub! I wanted to program the same. Could you move the module to the official humhub repo? So more people could be involved to help improving this module. Now it is a bit hidden. It's a pity...

**Comment by petersmithca** [comment]
Hi @michaelscheurer 

I am not the maintainer of the humhub repo, and as such have no ability to add my code to theirs.  I will ask if it can be added to the market place however, once I have investigated an issue mentioned.

**Comment by WebCrew** [comment]
Which issue You talking about Peter? The one that the chat is only availible at the dashboard view?

**Comment by petersmithca** [comment]
No, its that there is an option on the spaces menu to enable it, but there shouldnt be

**Comment by petersmithca** [comment]
You can see the issue here - and perhaps test my solution as well, my old computer died and I don't have my environment all set up yet - https://github.com/petersmithca/humhub-basic-chat/issues/3

**Comment by michaelscheurer** [comment]
@petersmithca would be great to find the chat-module in future on the market place and/or on their github repo. Thx for the big work.

**Comment by WebCrew** [comment]
@petersmithca thanks fopr the info I`ll test Your solution. Also let me know which hardware got crashed on Your PC. I have a lot of good used hardware parts from my PC`s. Should be no problem to give it to You - I dontt want money for it.

**Comment by petersmithca** [comment]
My video card died, but the pc was old anyway.  I bought a new laptop already, just dont have it all set up yet

**Comment by WebCrew** [comment]
ahhh ok but if You need a video card motherboard processors or RAM let me know. With me the parts are only lying around and it is a pity that they are not being used and create dust. :)

**Pull request merged**
