### PR TITLE
Update chat.css.bright

### PR DESCRIPTION
**Pull request by WebCrew**
Updated cause of message input field does not match with send button size. Now it should be ok.

### CODE REVIEW

**Comment by petersmithca** [comment]
Hi Andreas, does chat.css need an update too? I wasn't using the bright in
my example

**Comment by petersmithca** [comment]
Also, I think it needs to be 36 to allow for margins/padding at least it does on my install

**Comment by WebCrew** [comment]
Ok good to know it needs 36px, will update it now. Also chat.css and chat.css.bright will become the update :+1:

**Comment by petersmithca** [comment]
Could have just done in same pull request, but no biggie! closing this older one

**Pull request closed without merging**
